* Coredumping

How to create core dump file:

#+begin_src bash
  ulimit -c unlimited
  ./a.out 
  gdb ./a.out core
#+end_src

Then to debug
1. Use backtrace (=br=) command. It will map how the program crahsed.
#+begin_src gdb
  (gdb) bt
#0  0x00005585075b77de in ft_strlen ()
#1  0x00005585075b7488 in ft_strdup ()
#2  0x00005585075b6a21 in convert_s (content=0x7ffdcc9a6610, tokens=0x55853467c2d0) at token_helper.c:101
#3  0x00005585075b64a6 in apply_specifier (lst=0x55853467c2d0, args=0x7ffdcc9a6698) at token.c:164
#4  0x00005585075b6678 in read_token (format=0x7ffdcc9a6688, args=0x7ffdcc9a6698) at token.c:236
#5  0x00005585075b5ef4 in ft_printf (format=0x5585075b851b "") at ft_printf.c:17
#6  0x00005585075b39aa in main ()
#+end_src

2. Use frame (=frame 2=) command. It will map how the program crahsed.
#+begin_src gdb
(gdb) frame 2
#2  0x00005585075b6a21 in convert_s (content=0x7ffdcc9a6610, tokens=0x55853467c2d0) at token_helper.c:101
101		return (ft_strdup(*str));
#+end_src

3. Use (=list=) to display surrounding code in the frame.
4. displayer args (=infor args=).
5. displayer local variables (=info locals=).

Then revert core dump creation back to normal (0).
#+begin_src bash
ulimit -c 0
#+end_src

* GDB Printing List

Manual while iteration in gdb

#+begin_src gdb
set $node = lst
while $node != 0
  print $node->content
  set $node = $node->next
end
#+end_src

lst represent the HEAD node of the list.

Same idea also possible with user-defined function writing inside the =~/.gdbinit= file (or type in the session).

#+begin_src .gdbinit
define plist
  set $curr = $arg0
  while $curr != 0
    set $t = $curr->content
    set $t = (t_token *)$t
    p *$t
    set $curr = $curr->next
  end
end

document plist
  Print a linked list. Syntax: plist <head_pointer>
end
#+end_src

* Format String Attacks

* Design Decisions

Decided to only tokenize the conversion specifiers and print the strings without allocating memory. However I realized that original printf, prints an empty string if contains any invalid conversion specifier.

To fix this, decided to allocate strings with strjoin and allocate the conversion specifiers with tokenization. However better approach would be tokenize the whole text then print the whole token chain at once. This can be a future development task.

This would also fix the issue that, current system initialize a token_buf each time for read_token(). Here, bad design implemented because I was not aware that static globals are forbiden for this project. To be honest I still believe that making token_buf global is best approach for both memory and extendibility.

* Tester
Main design idea of this tester to have minimum amount of duplication while testing variadic functions and comapring two identical functions.

1. Only have TEST_STDOUT_FUNC func (macro func)
2. Directly compare two functions
3. No duplication while passing arguments
4. Supports multiple files and registering more tests
5. TEST_STDOUT_FUNC test both stdout and return values
